### ISSUE TITLE
Looking forward to ability to do Demo...

### ISSUE THREAD

**Issue by sjscotti** [dali92002/DocEnTR#1]
Hi
I read your paper on DocEnTR with interest and am looking forward to trying a demo (i.e., Using our Pretrained Models To Binarize A Single Degraded Image)... do you know when that will be available?
Thanks!

**Comment by dali92002** [comment]
Hello, Thanks for your interest in our work. The demo will be available shortly.

**Comment by sjscotti** [comment]
Thanks!... and a google collab notebook for the demo would also be nice! :-)
