### ISSUE TITLE
Getting Error while processing patches

### ISSUE THREAD

**Issue by mohansatishnomula** [dali92002/DocEnTR#10]
RuntimeError: The size of tensor a (192) must match the size of tensor b (768) at non-singleton dimension 2

**Comment by mohansatishnomula** [comment]
> RuntimeError: The size of tensor a (192) must match the size of tensor b (768) at non-singleton dimension 2

(0 / 62) processing patch...
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[78], line 10
      8 train_in = train_in.view(1,3,SPLITSIZE,SPLITSIZE).to(device)
      9 _ = torch.rand((train_in.shape)).to(device)
---> 10 loss,_, pred_pixel_values = model(train_in,_)
     11 rec_patches = pred_pixel_values
     12 rec_image = torch.squeeze(rearrange(rec_patches, 'b (h w) (p1 p2 c) -> b c (h p1) (w p2)', p1 = patch_size, p2 = patch_size,  h=image_size[0]//patch_size))

File ~\AppData\Local\anaconda3\Lib\site-packages\torch\nn\modules\module.py:1518, in Module._wrapped_call_impl(self, *args, **kwargs)
   1516     return self._compiled_call_impl(*args, **kwargs)  # type: ignore[misc]
   1517 else:
-> 1518     return self._call_impl(*args, **kwargs)

File ~\AppData\Local\anaconda3\Lib\site-packages\torch\nn\modules\module.py:1527, in Module._call_impl(self, *args, **kwargs)
   1522 # If we don't have any hooks, we want to skip the rest of the logic in
   1523 # this function, and just call forward.
   1524 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
   1525         or _global_backward_pre_hooks or _global_backward_hooks
   1526         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1527     return forward_call(*args, **kwargs)
   1529 try:
   1530     result = None

Cell In[11], line 50, in BinModel.forward(self, img, gt_img)
     48 # project pixel patches to tokens and add positions
     49 tokens = self.patch_to_emb(patches)
---> 50 tokens = tokens + self.encoder.pos_embedding[:, 1:(num_patches + 1)]
     52 # encode tokens by the encoder
     53 encoded_tokens = self.encoder.transformer(tokens)

RuntimeError: The size of tensor a (192) must match the size of tensor b (768) at non-singleton dimension 2

**Comment by dali92002** [comment]
can you elaborate more on the issue you had? which model did you download and use? and with patch size and model size did you choose?

**Comment by mohansatishnomula** [comment]
i have used the same weights that u shared but i got error in mismatch like  **_IncompatibleKeys(missing_keys, unexpected_keys)**

then i have changed the key name then i got all keys matched successful

while running the below code i got error
result = []
for patch_idx, p in enumerate(out_patches):
    print(f"({patch_idx} / {len(out_patches) - 1}) processing patch...")
    p = np.array(p, dtype='float32')
    train_in = torch.from_numpy(p)
 
    with torch.no_grad():
        train_in = train_in.view(1,3,SPLITSIZE,SPLITSIZE).to(device)
        _ = torch.rand((train_in.shape)).to(device)
        loss,_, pred_pixel_values = model(train_in,_)
        rec_patches = pred_pixel_values
        rec_image = torch.squeeze(rearrange(rec_patches, 'b (h w) (p1 p2 c) -> b c (h p1) (w p2)', p1 = patch_size, p2 = patch_size,  h=image_size[0]//patch_size))
        impred = rec_image.cpu().numpy()
        impred = np.transpose(impred, (1, 2, 0))
        for ch in range(3):
            impred[:,:,ch] = (impred[:,:,ch] *std[ch]) + mean[ch]
        impred[np.where(impred>1)] = 1
        impred[np.where(impred<0)] = 0
    result.append(impred)
    
    i got error as RuntimeError: The expanded size of the tensor (1024) must match the existing size (4096) at non-singleton dimension 1.  Target sizes: [-1, 1024, -1].  Tensor sizes: [1, 4096, 192]


then i changed the binmodel code to as

import torch
from torch import nn
import torch.nn.functional as F
from vit_pytorch.vit import Transformer


class BinModel(nn.Module):
    """
    The autoencoder model to enhance images in an image to image translation fashion.
    This code is built on top of the vit-pytorch code https://github.com/lucidrains/vit-pytorch.

    Args:
        encoder (model): the defined encoder, hete it is a ViT
        decoder_dim (int): decoder dim (embedding size)
        decoder_depth (int): number of decoder layers
        decoder_heads (int): number of decoder heads
        decoder_dim_head (int): decoder head dimension
    """
    def __init__(
        self,
        *,
        encoder,
        decoder_dim,
        decoder_depth = 1,
        decoder_heads = 8,
        decoder_dim_head = 64
    ):
        super().__init__()
        # extract hyperparameters and functions from the ViT encoder.
        self.encoder = encoder
        num_patches, encoder_dim = encoder.pos_embedding.shape[-2:]
        self.to_patch, self.patch_to_emb = encoder.to_patch_embedding[:2]
        pixel_values_per_patch = self.patch_to_emb.weight.shape[-1]

        # define your decoder here
        self.enc_to_dec = nn.Linear(encoder_dim, decoder_dim) if encoder_dim != decoder_dim else nn.Identity()
        self.mask_token = nn.Parameter(torch.randn(decoder_dim))
        self.decoder = Transformer(dim = decoder_dim, depth = decoder_depth, heads = decoder_heads, dim_head = decoder_dim_head, mlp_dim = decoder_dim * 4)
        self.decoder_pos_emb = nn.Embedding(num_patches, decoder_dim)
        self.to_pixels = nn.Linear(decoder_dim, pixel_values_per_patch)

    def forward(self, img, gt_img = None):

        # project pixel patches to tokens and add positions
        tokens = self.encoder.to_patch_embedding(img)
        print(tokens.shape)
        print(self.encoder.pos_embedding.shape)
        print( self.encoder.pos_embedding[:, 1:(num_patches + 1)].shape)
        tokens = tokens + self.encoder.pos_embedding[:, 1:(num_patches + 1)]
        # Add resized positional embeddings to tokens        

        # encode tokens by the encoder
        encoded_tokens = self.encoder.transformer(tokens)

        # project encoder to decoder dimensions, if they are not equal.
        decoder_tokens = self.enc_to_dec(encoded_tokens)

        # decode tokens with decoder
        decoded_tokens = self.decoder(decoder_tokens)

        # project tokens to pixels
        pred_pixel_values = self.to_pixels(decoded_tokens)

        # calculate the loss with gt
        if gt_img is not None:
            gt_patches = self.to_patch(gt_img)
            loss = F.mse_loss(pred_pixel_values, gt_patches)

            return loss, pred_pixel_values
        else:
            return pred_pixel_values
    
So now i am getting error as 

0 / 62) processing patch...
RuntimeError Traceback (most recent call last)
Cell In[78], line 10
8 train_in = train_in.view(1,3,SPLITSIZE,SPLITSIZE).to(device)
9 _ = torch.rand((train_in.shape)).to(device)
---> 10 loss,, pred_pixel_values = model(train_in,)
11 rec_patches = pred_pixel_values
12 rec_image = torch.squeeze(rearrange(rec_patches, 'b (h w) (p1 p2 c) -> b c (h p1) (w p2)', p1 = patch_size, p2 = patch_size, h=image_size[0]//patch_size))

File ~\AppData\Local\anaconda3\Lib\site-packages\torch\nn\modules\module.py:1518, in Module._wrapped_call_impl(self, *args, **kwargs)
1516 return self._compiled_call_impl(*args, **kwargs) # type: ignore[misc]
1517 else:
-> 1518 return self._call_impl(*args, **kwargs)

File ~\AppData\Local\anaconda3\Lib\site-packages\torch\nn\modules\module.py:1527, in Module._call_impl(self, *args, **kwargs)
1522 # If we don't have any hooks, we want to skip the rest of the logic in
1523 # this function, and just call forward.
1524 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
1525 or _global_backward_pre_hooks or _global_backward_hooks
1526 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1527 return forward_call(*args, **kwargs)
1529 try:
1530 result = None

Cell In[11], line 50, in BinModel.forward(self, img, gt_img)
48 # project pixel patches to tokens and add positions
49 tokens = self.patch_to_emb(patches)
---> 50 tokens = tokens + self.encoder.pos_embedding[:, 1:(num_patches + 1)]
52 # encode tokens by the encoder
53 encoded_tokens = self.encoder.transformer(tokens)

RuntimeError: The size of tensor a (192) must match the size of tensor b (768) at non-singleton dimension 2

**Comment by mohansatishnomula** [comment]
"base": {
        "ENCODERLAYERS": 6,
        "ENCODERHEADS": 8,
        "ENCODERDIM": 768,
        "patch_size": 8,
    },

**Comment by mohansatishnomula** [comment]
Issue Resolved thank you

there was some version mismatch of transformers
