### ISSUE TITLE
[question] training epochs and GPU resource cost

### ISSUE THREAD

**Issue by cactusgame** [dali92002/DocEnTR#11]
I'd like to express my gratitude to the author for the paper and codes.

May I ask, how many GPU hours were actually utilized in training the model presented in the official example using this data? Additionally, how many epochs were trained? 
Thanks anyway

**Comment by biswassanket** [comment]
Hey, thanks a lot for your interest and appreciation. I guess with a 24 GB RTX 3090, you could fine-tune a model ViT-Base for 150 epochs and it would take around 2 days.  If you do distributed parallel training, you could make it faster and train with a larger batch size.

**Comment by cactusgame** [comment]
Thanks very much! I'll have a try ~

> Hey, thanks a lot for your interest and appreciation. I guess with a 24 GB RTX 3090, you could fine-tune a model ViT-Base for 150 epochs and it would take around 2 days. If you do distributed parallel training, you could make it faster and train with a larger batch size.
