### ISSUE TITLE
Process a single image or multiple images without GT

### ISSUE THREAD

**Issue by rbbernardino** [dali92002/DocEnTR#2]
Dear Authors,

Your solution seems to be remarkably good and we would like to include in our tests for a new publication. I believe your solution has potential to be among the best tested.

If providing a way of running the code for a single image is too much for now, could you modify your dibco test code in a way that it reads several images without ground-truth?

**Comment by dali92002** [comment]
Hi, the demo is now added in the file demo.ipynb
