### ISSUE TITLE
Multi core

### ISSUE THREAD

**Issue by grungert** [dali92002/DocEnTR#3]
Hi, great paper and thank you for sharing the code.

I was able to run test.py. I did some code correction for paths in utils.py. I needed to update path. My root folder for dataset was difrent:
gt_folder = 'data/DIBCOSETS/'+valid_data+'/gt_imgs' 

I test it on my PC with NVIDIA GeForce GTX 1660 Ti (6GB GDDR6 memory). In the test folder were 266 images (255x255) and it took ~27sec to process. 

The second test was on the CPU. And I can see that use only one core. The time for processing is ~12min=720sec.

Is there a way to run this model prediction on a multi-core CPU and optimize time?

And I'm hoping for code "Process a single image or multiple images without GT" (https://github.com/dali92002/DocEnTR/issues/2

Thanks again

**Comment by biswassanket** [comment]
Hi, the code was originally written to optimize performance time on GPU computation, and not for a CPU-only (multi-core) scenario as you mentioned. But indeed that would be interesting to try too. Regarding  "processing single image.multiple image inference without GT" we have launched a simple primary version of the demo.ipynb for trial. Hope this addresses your issues.
