### ISSUE TITLE
What is the `masking_ratio`?

### ISSUE THREAD

**Issue by theotheo** [dali92002/DocEnTR#7]
Hello! Could you help me figure out this part of code?
Here is created `masking_ratio` variable, but it not used anywhere else. What was the intended purpose of these lines? Maybe a different model was meant originally here?

https://github.com/dali92002/DocEnTR/blob/2e09b9e4e904802fb83f6b8e8176bdca150c53f9/models/binae.py#L21-L22

**Comment by dali92002** [comment]
Tha came from a different model, it was not necessary for ours, we remove it now after the refactoring ..

**Comment by theotheo** [comment]
Thank you! Now it's clear.
