### ISSUE TITLE
Links to the models do not work

### ISSUE THREAD

**Issue by epolina** [dali92002/DocEnTR#9]
Hi, I tried to download the models today using the links in the repo but it says that the file no longer exists. Were they taken down?

**Comment by dali92002** [comment]
yes, they are down now because we lost our drive storage. We will recover them soon! if you need just inference you can use our demo https://replicate.com/cjwbw/docentr

**Comment by Chirag-Mphasis** [comment]
Are the weights back up? The links to the weights are still broken

**Comment by RylonW** [comment]
Hope to recover weights.

**Comment by 00sapo** [comment]
Same here, having the weights would be helpful!

**Comment by abiudrodas** [comment]
Hi, do you have any new about this?

**Comment by mrvoh** [comment]
I would also very much appreciate having access to the model weights. Thanks already!

**Comment by satya394** [comment]
Thanks for your paper and the code 🙂

Can you please let us know if you're open to sharing the model weights. I can help you with hosting the model weights on Hugging Face if necessary

**Comment by biswassanket** [comment]
Hello all, we are in the process of recovering the weights and uploading them by next week. Sorry for the inconvenience as we lost them as the uploaded account expired! Thanks for being patient :)

**Comment by dali92002** [comment]
Hello everyone. We manage to recover the weighs for the models tested on DIBCO 2012, 2017 and 2018, the links are now updated and accessible. We couldn't recover the weights for the 2011 model.  I hope this helps and thank you for your interest in our work.
